### ISSUE TITLE
Number signs

### ISSUE THREAD

**Issue by deathaxe** [jrappen/sublime-json#2]
The scope to use for number signs was explicitly discussed during last dev cycle and the probolal to use a `constant.numeric.sign` sub scope was rejected in favor of `keyword.operator.arithmetic`.

see: https://github.com/jrappen/sublime-json/blob/f3cee02011dab016d9bbb2c82f8a335d230f9d7c/JSON/JSON5.sublime-syntax#L74

The reason is many syntaxes not really being able to distinguish normal arithmetic operators from number signs, so the same scope is used for both for consistent highlighting across syntaxes.

**Comment by jrappen** [comment]
There are no operators in JSON, though. SublimeHQ should just add the scope to their schemes.

**Comment by deathaxe** [comment]
This has been discussed. The `keyword.operator` is the way to go.

**Comment by jrappen** [comment]
Yes. They chose the wrong way im my opinion.

**Comment by deathaxe** [comment]
Maybe, but any syntax which wants to be part of it needs to follow.

**Comment by jrappen** [comment]
Ok. I'll fix it later.

**Comment by jrappen** [comment]
I talked to Jon, he said if my PR passes review in the Packages repo, it would be a reason for them to add the scopes in their schemes.

**Comment by jrappen** [comment]
He said he had no idea, why <https://github.com/sublimehq/Packages/commit/04d5b6e> was made.
